version: '3.1'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: moneygement
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"