spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    use_sql_comments: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false
  ai:
    openai:
      api-key: testKey
    chat:
      options:
        model: gpt-4o
        temperature: 0.6
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org:
        hibernate:
          SQL: DEBUG
          type: TRACE
      org.hibernate.engine.query.spi: DEBUG
server:
  port: 8080


