spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/moneygement
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
