name: Deploy

on:
  push:
    branches: [ main ]

env:
  REPO: moneygement-api-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./moneygement-api-server

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./moneygement-api-server

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./moneygement-api-server
          file: ./moneygement-api-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest